export const MockData = [
  {
    id: "1",
    name: "Prosperidad para marcas personales",
    description:
      "El objetivo del curso es proporcionar a los participantes herramientas y estrategias prácticas para mejorar su marca personal y aumentar su visibilidad, autoridad y influencia en su industria o nicho de mercado. Además, el curso puede abordar temas como la definición de objetivos, la planificación de carrera, la gestión de la reputación en línea y la construcción de una red sólida de contactos.",
    stock: 5,
    categoryName: "Desarrollo personal",
    slug: "desarrollo-personal",
    image: "https://via.placeholder.com/1280x720.jpg",
    author: "Mariela Villalobos",
    price: 19.99,
  },
  {
    id: "2",
    name: "Curso 2",
    description: "Desripcion del curso 2",
    stock: 1,
    categoryName: "Desarrollo personal",
    slug: "desarrollo-personal",
    image: "https://via.placeholder.com/1280x720.jpg",
    author: "Hoyver Villasmil",
    price: 19.99,
  },
  {
    id: "3",
    name: "Curso 3",
    description: "Desripcion del curso 3",
    stock: 3,
    categoryName: "Branding",
    slug: "branding",
    image: "https://via.placeholder.com/1280x720.jpg",
    author: "Mile Conde",
    price: 19.99,
  },
  {
    id: "4",
    name: "Curso 4",
    description: "Desripcion del curso 4",
    stock: 4,
    categoryName: "Branding",
    slug: "branding",
    image: "https://via.placeholder.com/1280x720.jpg",
    author: "Vidal Sarmiento",
    price: 19.99,
  },
];
