export const MockData = [
  {
    id: "1",
    name: "Prosperidad para marcas personales",
    description: "Desripcion del curso 1",
    stock: 5,
    category: "Desarrollo personal",
    image: "https://via.placeholder.com/640x360.jpg",
    author: "Mariela Villalobos",
  },
  {
    id: "2",
    name: "Curso 2",
    description: "Desripcion del curso 2",
    stock: 1,
    cat: "Desarrollo personal",
    image: "",
    author: "",
  },
  {
    id: "3",
    name: "Curso 3",
    description: "Desripcion del curso 3",
    stock: 3,
    cat: "Desarrollo personal",
    image: "",
    author: "",
  },
  {
    id: "4",
    name: "Curso 4",
    description: "Desripcion del curso 4",
    stock: 4,
    cat: "Desarrollo personal",
    image: "",
    author: "",
  },
];
